// Professional Food Database — 250+ foods with accurate per-100g macros
// Data sourced from FatSecret, USDA FoodData Central & regional nutrition databases

export interface FoodData {
  id: string;
  name: string;
  nameAr?: string;
  category: string;
  calories: number;
  protein: number;
  carbs: number;
  fats: number;
  unit: string;
}

export const FOODS: FoodData[] = [
  // ============== PROTEINS — Poultry ==============
  { id: 'p1', name: 'Chicken Breast (Grilled)', category: 'Protein', calories: 165, protein: 31, carbs: 0, fats: 3.6, unit: '100g' },
  { id: 'p2', name: 'Chicken Thigh (Skinless)', category: 'Protein', calories: 209, protein: 26, carbs: 0, fats: 10.9, unit: '100g' },
  { id: 'p3', name: 'Chicken Wings', category: 'Protein', calories: 203, protein: 30.5, carbs: 0, fats: 8.1, unit: '100g' },
  { id: 'p4', name: 'Chicken Drumstick', category: 'Protein', calories: 172, protein: 28.3, carbs: 0, fats: 5.7, unit: '100g' },
  { id: 'p5', name: 'Whole Roast Chicken', category: 'Protein', calories: 190, protein: 29, carbs: 0, fats: 7.4, unit: '100g' },
  { id: 'p6', name: 'Turkey Breast', category: 'Protein', calories: 135, protein: 30, carbs: 0, fats: 1, unit: '100g' },
  { id: 'p7', name: 'Duck Breast', category: 'Protein', calories: 201, protein: 23.5, carbs: 0, fats: 11.2, unit: '100g' },

  // ============== PROTEINS — Beef ==============
  { id: 'p10', name: 'Ground Beef (90% lean)', category: 'Protein', calories: 176, protein: 20, carbs: 0, fats: 10, unit: '100g' },
  { id: 'p11', name: 'Ground Beef (80% lean)', category: 'Protein', calories: 254, protein: 17.2, carbs: 0, fats: 20, unit: '100g' },
  { id: 'p12', name: 'Ribeye Steak', category: 'Protein', calories: 291, protein: 24, carbs: 0, fats: 21, unit: '100g' },
  { id: 'p13', name: 'Sirloin Steak', category: 'Protein', calories: 200, protein: 27, carbs: 0, fats: 9.3, unit: '100g' },
  { id: 'p14', name: 'Beef Tenderloin (Filet)', category: 'Protein', calories: 218, protein: 26, carbs: 0, fats: 12, unit: '100g' },
  { id: 'p15', name: 'Beef Liver', category: 'Protein', calories: 135, protein: 20, carbs: 3.9, fats: 3.6, unit: '100g' },
  { id: 'p16', name: 'Beef Brisket', category: 'Protein', calories: 246, protein: 21, carbs: 0, fats: 17, unit: '100g' },
  { id: 'p17', name: 'Corned Beef', category: 'Protein', calories: 250, protein: 18, carbs: 0.5, fats: 19, unit: '100g' },

  // ============== PROTEINS — Lamb ==============
  { id: 'p20', name: 'Lamb Chop (Grilled)', category: 'Protein', calories: 282, protein: 25, carbs: 0, fats: 20, unit: '100g' },
  { id: 'p21', name: 'Lamb Leg (Roasted)', category: 'Protein', calories: 230, protein: 26, carbs: 0, fats: 13, unit: '100g' },
  { id: 'p22', name: 'Lamb Shoulder', category: 'Protein', calories: 258, protein: 22, carbs: 0, fats: 18.5, unit: '100g' },
  { id: 'p23', name: 'Lamb Mince', category: 'Protein', calories: 282, protein: 17, carbs: 0, fats: 23, unit: '100g' },

  // ============== PROTEINS — Fish & Seafood ==============
  { id: 'p30', name: 'Salmon Fillet', category: 'Protein', calories: 208, protein: 20, carbs: 0, fats: 13, unit: '100g' },
  { id: 'p31', name: 'Tuna (Canned in Water)', category: 'Protein', calories: 116, protein: 26, carbs: 0, fats: 0.8, unit: '100g' },
  { id: 'p32', name: 'Tuna Steak (Fresh)', category: 'Protein', calories: 132, protein: 28, carbs: 0, fats: 1.3, unit: '100g' },
  { id: 'p33', name: 'Shrimp', category: 'Protein', calories: 99, protein: 24, carbs: 0.2, fats: 0.3, unit: '100g' },
  { id: 'p34', name: 'Tilapia', category: 'Protein', calories: 96, protein: 20, carbs: 0, fats: 1.7, unit: '100g' },
  { id: 'p35', name: 'Cod Fillet', category: 'Protein', calories: 82, protein: 18, carbs: 0, fats: 0.7, unit: '100g' },
  { id: 'p36', name: 'Sardines (Canned)', category: 'Protein', calories: 208, protein: 25, carbs: 0, fats: 11, unit: '100g' },
  { id: 'p37', name: 'Mackerel', category: 'Protein', calories: 205, protein: 19, carbs: 0, fats: 14, unit: '100g' },
  { id: 'p38', name: 'Sea Bass', category: 'Protein', calories: 124, protein: 24, carbs: 0, fats: 2.6, unit: '100g' },
  { id: 'p39', name: 'Calamari (Grilled)', category: 'Protein', calories: 175, protein: 18, carbs: 7.8, fats: 7.5, unit: '100g' },
  { id: 'p40', name: 'Crab Meat', category: 'Protein', calories: 97, protein: 19, carbs: 0, fats: 1.5, unit: '100g' },

  // ============== EGGS & DAIRY ==============
  { id: 'd1', name: 'Whole Egg', category: 'Dairy', calories: 155, protein: 13, carbs: 1.1, fats: 11, unit: '100g' },
  { id: 'd2', name: 'Egg White', category: 'Dairy', calories: 52, protein: 11, carbs: 0.7, fats: 0.2, unit: '100g' },
  { id: 'd3', name: 'Greek Yogurt (0% fat)', category: 'Dairy', calories: 59, protein: 10, carbs: 3.6, fats: 0.4, unit: '100g' },
  { id: 'd4', name: 'Greek Yogurt (Full Fat)', category: 'Dairy', calories: 97, protein: 9, carbs: 3.6, fats: 5, unit: '100g' },
  { id: 'd5', name: 'Cottage Cheese', category: 'Dairy', calories: 98, protein: 11, carbs: 3.4, fats: 4.3, unit: '100g' },
  { id: 'd6', name: 'Whole Milk', category: 'Dairy', calories: 61, protein: 3.2, carbs: 4.8, fats: 3.3, unit: '100g' },
  { id: 'd7', name: 'Skim Milk', category: 'Dairy', calories: 34, protein: 3.4, carbs: 5, fats: 0.1, unit: '100g' },
  { id: 'd8', name: 'Cheddar Cheese', category: 'Dairy', calories: 403, protein: 25, carbs: 1.3, fats: 33, unit: '100g' },
  { id: 'd9', name: 'Mozzarella', category: 'Dairy', calories: 280, protein: 28, carbs: 3.1, fats: 17, unit: '100g' },
  { id: 'd10', name: 'Feta Cheese', category: 'Dairy', calories: 264, protein: 14, carbs: 4.1, fats: 21, unit: '100g' },
  { id: 'd11', name: 'Parmesan', category: 'Dairy', calories: 431, protein: 38, carbs: 4.1, fats: 29, unit: '100g' },
  { id: 'd12', name: 'Whey Protein Powder', category: 'Dairy', calories: 400, protein: 80, carbs: 10, fats: 5, unit: '100g' },
  { id: 'd13', name: 'Cream Cheese', category: 'Dairy', calories: 342, protein: 6, carbs: 4, fats: 34, unit: '100g' },
  { id: 'd14', name: 'Labneh', category: 'Dairy', calories: 160, protein: 6, carbs: 5, fats: 13, unit: '100g' },
  { id: 'd15', name: 'Roumy Cheese', category: 'Dairy', calories: 380, protein: 28, carbs: 2, fats: 29, unit: '100g' },
  { id: 'd16', name: 'Halloumi Cheese', category: 'Dairy', calories: 321, protein: 25, carbs: 2.6, fats: 24, unit: '100g' },

  // ============== GRAINS & CARBS ==============
  { id: 'g1', name: 'White Rice (Cooked)', category: 'Carbs', calories: 130, protein: 2.7, carbs: 28, fats: 0.3, unit: '100g' },
  { id: 'g2', name: 'Brown Rice (Cooked)', category: 'Carbs', calories: 112, protein: 2.3, carbs: 24, fats: 0.8, unit: '100g' },
  { id: 'g3', name: 'Basmati Rice (Cooked)', category: 'Carbs', calories: 121, protein: 3.5, carbs: 25, fats: 0.4, unit: '100g' },
  { id: 'g4', name: 'Oats (Dry)', category: 'Carbs', calories: 389, protein: 17, carbs: 66, fats: 7, unit: '100g' },
  { id: 'g5', name: 'Pasta (Cooked)', category: 'Carbs', calories: 131, protein: 5, carbs: 25, fats: 1.1, unit: '100g' },
  { id: 'g6', name: 'Whole Wheat Bread', category: 'Carbs', calories: 247, protein: 13, carbs: 41, fats: 3.4, unit: '100g' },
  { id: 'g7', name: 'White Bread', category: 'Carbs', calories: 265, protein: 9, carbs: 49, fats: 3.2, unit: '100g' },
  { id: 'g8', name: 'Baladi Bread', category: 'Carbs', calories: 275, protein: 9.5, carbs: 56, fats: 1.2, unit: '100g' },
  { id: 'g9', name: 'Pita Bread', category: 'Carbs', calories: 275, protein: 9.1, carbs: 55, fats: 1.2, unit: '100g' },
  { id: 'g10', name: 'Quinoa (Cooked)', category: 'Carbs', calories: 120, protein: 4.4, carbs: 21, fats: 1.9, unit: '100g' },
  { id: 'g11', name: 'Sweet Potato (Baked)', category: 'Carbs', calories: 86, protein: 1.6, carbs: 20, fats: 0.1, unit: '100g' },
  { id: 'g12', name: 'Regular Potato (Baked)', category: 'Carbs', calories: 93, protein: 2.5, carbs: 21, fats: 0.1, unit: '100g' },
  { id: 'g13', name: 'French Fries', category: 'Carbs', calories: 312, protein: 3.4, carbs: 41, fats: 15, unit: '100g' },
  { id: 'g14', name: 'Corn Tortilla', category: 'Carbs', calories: 218, protein: 6, carbs: 44, fats: 3, unit: '100g' },
  { id: 'g15', name: 'Couscous (Cooked)', category: 'Carbs', calories: 112, protein: 3.8, carbs: 23, fats: 0.2, unit: '100g' },
  { id: 'g16', name: 'Bulgur (Cooked)', category: 'Carbs', calories: 83, protein: 3.1, carbs: 19, fats: 0.2, unit: '100g' },
  { id: 'g17', name: 'Vermicelli (Shaeriya)', category: 'Carbs', calories: 351, protein: 12, carbs: 72, fats: 1.5, unit: '100g' },
  { id: 'g18', name: 'Cornflakes', category: 'Carbs', calories: 357, protein: 7, carbs: 84, fats: 0.4, unit: '100g' },

  // ============== FRUITS ==============
  { id: 'fr1', name: 'Banana', category: 'Fruits', calories: 89, protein: 1.1, carbs: 23, fats: 0.3, unit: '100g' },
  { id: 'fr2', name: 'Apple', category: 'Fruits', calories: 52, protein: 0.3, carbs: 14, fats: 0.2, unit: '100g' },
  { id: 'fr3', name: 'Strawberries', category: 'Fruits', calories: 32, protein: 0.7, carbs: 7.7, fats: 0.3, unit: '100g' },
  { id: 'fr4', name: 'Blueberries', category: 'Fruits', calories: 57, protein: 0.7, carbs: 14, fats: 0.3, unit: '100g' },
  { id: 'fr5', name: 'Mango', category: 'Fruits', calories: 60, protein: 0.8, carbs: 15, fats: 0.4, unit: '100g' },
  { id: 'fr6', name: 'Orange', category: 'Fruits', calories: 47, protein: 0.9, carbs: 12, fats: 0.1, unit: '100g' },
  { id: 'fr7', name: 'Watermelon', category: 'Fruits', calories: 30, protein: 0.6, carbs: 7.6, fats: 0.2, unit: '100g' },
  { id: 'fr8', name: 'Grapes', category: 'Fruits', calories: 69, protein: 0.7, carbs: 18, fats: 0.2, unit: '100g' },
  { id: 'fr9', name: 'Pineapple', category: 'Fruits', calories: 50, protein: 0.5, carbs: 13, fats: 0.1, unit: '100g' },
  { id: 'fr10', name: 'Dates', category: 'Fruits', calories: 277, protein: 1.8, carbs: 75, fats: 0.2, unit: '100g' },
  { id: 'fr11', name: 'Guava', category: 'Fruits', calories: 68, protein: 2.6, carbs: 14, fats: 1, unit: '100g' },
  { id: 'fr12', name: 'Pomegranate', category: 'Fruits', calories: 83, protein: 1.7, carbs: 19, fats: 1.2, unit: '100g' },
  { id: 'fr13', name: 'Fig (Fresh)', category: 'Fruits', calories: 74, protein: 0.8, carbs: 19, fats: 0.3, unit: '100g' },
  { id: 'fr14', name: 'Cantaloupe', category: 'Fruits', calories: 34, protein: 0.8, carbs: 8.2, fats: 0.2, unit: '100g' },
  { id: 'fr15', name: 'Peach', category: 'Fruits', calories: 39, protein: 0.9, carbs: 10, fats: 0.3, unit: '100g' },

  // ============== VEGETABLES ==============
  { id: 'v1', name: 'Broccoli', category: 'Vegetables', calories: 34, protein: 2.8, carbs: 7, fats: 0.4, unit: '100g' },
  { id: 'v2', name: 'Spinach', category: 'Vegetables', calories: 23, protein: 2.9, carbs: 3.6, fats: 0.4, unit: '100g' },
  { id: 'v3', name: 'Avocado', category: 'Vegetables', calories: 160, protein: 2, carbs: 8.5, fats: 15, unit: '100g' },
  { id: 'v4', name: 'Cucumber', category: 'Vegetables', calories: 15, protein: 0.7, carbs: 3.6, fats: 0.1, unit: '100g' },
  { id: 'v5', name: 'Tomato', category: 'Vegetables', calories: 18, protein: 0.9, carbs: 3.9, fats: 0.2, unit: '100g' },
  { id: 'v6', name: 'Carrots', category: 'Vegetables', calories: 41, protein: 0.9, carbs: 10, fats: 0.2, unit: '100g' },
  { id: 'v7', name: 'Bell Pepper', category: 'Vegetables', calories: 31, protein: 1, carbs: 6, fats: 0.3, unit: '100g' },
  { id: 'v8', name: 'Mushrooms', category: 'Vegetables', calories: 22, protein: 3.1, carbs: 3.3, fats: 0.3, unit: '100g' },
  { id: 'v9', name: 'Zucchini', category: 'Vegetables', calories: 17, protein: 1.2, carbs: 3.1, fats: 0.3, unit: '100g' },
  { id: 'v10', name: 'Kale', category: 'Vegetables', calories: 49, protein: 4.3, carbs: 9, fats: 0.9, unit: '100g' },
  { id: 'v11', name: 'Okra (Bamia)', category: 'Vegetables', calories: 33, protein: 1.9, carbs: 7, fats: 0.2, unit: '100g' },
  { id: 'v12', name: 'Eggplant', category: 'Vegetables', calories: 25, protein: 1, carbs: 6, fats: 0.2, unit: '100g' },
  { id: 'v13', name: 'Onion', category: 'Vegetables', calories: 40, protein: 1.1, carbs: 9, fats: 0.1, unit: '100g' },
  { id: 'v14', name: 'Garlic', category: 'Vegetables', calories: 149, protein: 6.4, carbs: 33, fats: 0.5, unit: '100g' },
  { id: 'v15', name: 'Cabbage', category: 'Vegetables', calories: 25, protein: 1.3, carbs: 6, fats: 0.1, unit: '100g' },
  { id: 'v16', name: 'Cauliflower', category: 'Vegetables', calories: 25, protein: 1.9, carbs: 5, fats: 0.3, unit: '100g' },
  { id: 'v17', name: 'Lettuce', category: 'Vegetables', calories: 15, protein: 1.4, carbs: 2.9, fats: 0.2, unit: '100g' },
  { id: 'v18', name: 'Green Beans', category: 'Vegetables', calories: 31, protein: 1.8, carbs: 7, fats: 0.1, unit: '100g' },
  { id: 'v19', name: 'Peas (Green)', category: 'Vegetables', calories: 81, protein: 5.4, carbs: 14, fats: 0.4, unit: '100g' },
  { id: 'v20', name: 'Corn (Sweet)', category: 'Vegetables', calories: 86, protein: 3.3, carbs: 19, fats: 1.2, unit: '100g' },

  // ============== FATS & NUTS ==============
  { id: 'f1', name: 'Peanut Butter', category: 'Fats', calories: 588, protein: 25, carbs: 20, fats: 50, unit: '100g' },
  { id: 'f2', name: 'Almonds', category: 'Fats', calories: 579, protein: 21, carbs: 22, fats: 50, unit: '100g' },
  { id: 'f3', name: 'Walnuts', category: 'Fats', calories: 654, protein: 15, carbs: 14, fats: 65, unit: '100g' },
  { id: 'f4', name: 'Cashews', category: 'Fats', calories: 553, protein: 18, carbs: 30, fats: 44, unit: '100g' },
  { id: 'f5', name: 'Olive Oil', category: 'Fats', calories: 884, protein: 0, carbs: 0, fats: 100, unit: '100g' },
  { id: 'f6', name: 'Coconut Oil', category: 'Fats', calories: 862, protein: 0, carbs: 0, fats: 100, unit: '100g' },
  { id: 'f7', name: 'Chia Seeds', category: 'Fats', calories: 486, protein: 17, carbs: 42, fats: 31, unit: '100g' },
  { id: 'f8', name: 'Flax Seeds', category: 'Fats', calories: 534, protein: 18, carbs: 29, fats: 42, unit: '100g' },
  { id: 'f9', name: 'Butter', category: 'Fats', calories: 717, protein: 0.9, carbs: 0.1, fats: 81, unit: '100g' },
  { id: 'f10', name: 'Tahini', category: 'Fats', calories: 595, protein: 17, carbs: 21, fats: 54, unit: '100g' },
  { id: 'f11', name: 'Ghee (Samna)', category: 'Fats', calories: 876, protein: 0, carbs: 0, fats: 99.5, unit: '100g' },
  { id: 'f12', name: 'Pistachios', category: 'Fats', calories: 560, protein: 20, carbs: 28, fats: 45, unit: '100g' },
  { id: 'f13', name: 'Sunflower Seeds', category: 'Fats', calories: 584, protein: 21, carbs: 20, fats: 51, unit: '100g' },
  { id: 'f14', name: 'Peanuts (Roasted)', category: 'Fats', calories: 567, protein: 26, carbs: 16, fats: 49, unit: '100g' },
  { id: 'f15', name: 'Hazelnuts', category: 'Fats', calories: 628, protein: 15, carbs: 17, fats: 61, unit: '100g' },

  // ============== LEGUMES ==============
  { id: 'lg1', name: 'Lentils (Cooked)', category: 'Legumes', calories: 116, protein: 9, carbs: 20, fats: 0.4, unit: '100g' },
  { id: 'lg2', name: 'Chickpeas (Cooked)', category: 'Legumes', calories: 164, protein: 8.9, carbs: 27, fats: 2.6, unit: '100g' },
  { id: 'lg3', name: 'Black Beans (Cooked)', category: 'Legumes', calories: 132, protein: 8.9, carbs: 24, fats: 0.5, unit: '100g' },
  { id: 'lg4', name: 'Kidney Beans (Cooked)', category: 'Legumes', calories: 127, protein: 8.7, carbs: 23, fats: 0.5, unit: '100g' },
  { id: 'lg5', name: 'Fava Beans (Ful - Cooked)', category: 'Legumes', calories: 110, protein: 8, carbs: 19, fats: 0.4, unit: '100g' },
  { id: 'lg6', name: 'White Beans (Fasolia)', category: 'Legumes', calories: 139, protein: 9.7, carbs: 25, fats: 0.5, unit: '100g' },
  { id: 'lg7', name: 'Black-eyed Peas (Lobia)', category: 'Legumes', calories: 116, protein: 7.7, carbs: 21, fats: 0.5, unit: '100g' },
  { id: 'lg8', name: 'Green Lentils (Cooked)', category: 'Legumes', calories: 116, protein: 9, carbs: 20, fats: 0.4, unit: '100g' },
  { id: 'lg9', name: 'Edamame', category: 'Legumes', calories: 121, protein: 12, carbs: 9, fats: 5, unit: '100g' },

  // ============== 🇪🇬 EGYPTIAN DISHES ==============
  { id: 'eg1', name: 'Koshari', category: 'Egyptian', calories: 148, protein: 5, carbs: 26, fats: 2.5, unit: '100g' },
  { id: 'eg2', name: 'Ful Medames', category: 'Egyptian', calories: 120, protein: 8, carbs: 18, fats: 2, unit: '100g' },
  { id: 'eg3', name: "Ta'ameya (Egyptian Falafel)", category: 'Egyptian', calories: 300, protein: 10, carbs: 30, fats: 16, unit: '100g' },
  { id: 'eg4', name: 'Molokhia (Soup)', category: 'Egyptian', calories: 50, protein: 2, carbs: 5, fats: 2.5, unit: '100g' },
  { id: 'eg5', name: 'Mahshi (Stuffed Vegetables)', category: 'Egyptian', calories: 135, protein: 5, carbs: 18, fats: 5, unit: '100g' },
  { id: 'eg6', name: 'Hawawshi', category: 'Egyptian', calories: 280, protein: 16, carbs: 22, fats: 14, unit: '100g' },
  { id: 'eg7', name: 'Kofta Mashwia (Grilled)', category: 'Egyptian', calories: 240, protein: 18, carbs: 4, fats: 17, unit: '100g' },
  { id: 'eg8', name: 'Alexandrian Liver (Kibda)', category: 'Egyptian', calories: 155, protein: 22, carbs: 5, fats: 5, unit: '100g' },
  { id: 'eg9', name: 'Fattah', category: 'Egyptian', calories: 230, protein: 7, carbs: 28, fats: 10, unit: '100g' },
  { id: 'eg10', name: 'Besara', category: 'Egyptian', calories: 90, protein: 6, carbs: 12, fats: 2, unit: '100g' },
  { id: 'eg11', name: 'Bamia Stew', category: 'Egyptian', calories: 85, protein: 5, carbs: 8, fats: 4, unit: '100g' },
  { id: 'eg12', name: 'Fasolia Stew (White Beans)', category: 'Egyptian', calories: 110, protein: 6, carbs: 15, fats: 3, unit: '100g' },
  { id: 'eg13', name: 'Mombar', category: 'Egyptian', calories: 145, protein: 8, carbs: 16, fats: 5.5, unit: '100g' },
  { id: 'eg14', name: 'Roz Moammar', category: 'Egyptian', calories: 200, protein: 5, carbs: 28, fats: 8, unit: '100g' },
  { id: 'eg15', name: 'Kabab (Egyptian Grilled)', category: 'Egyptian', calories: 215, protein: 22, carbs: 2, fats: 13, unit: '100g' },
  { id: 'eg16', name: 'Fiteer Meshaltet', category: 'Egyptian', calories: 350, protein: 6, carbs: 45, fats: 16, unit: '100g' },
  { id: 'eg17', name: 'Koshary with Dakka Sauce', category: 'Egyptian', calories: 165, protein: 5.5, carbs: 28, fats: 3.5, unit: '100g' },
  { id: 'eg18', name: 'Moussaka (Egyptian)', category: 'Egyptian', calories: 105, protein: 3.5, carbs: 10, fats: 6, unit: '100g' },
  { id: 'eg19', name: 'Shakshouka', category: 'Egyptian', calories: 95, protein: 6, carbs: 7, fats: 5, unit: '100g' },
  { id: 'eg20', name: 'Feteer with Cheese', category: 'Egyptian', calories: 380, protein: 10, carbs: 40, fats: 20, unit: '100g' },
  { id: 'eg21', name: 'Egyptian Rice with Vermicelli', category: 'Egyptian', calories: 150, protein: 3, carbs: 28, fats: 3, unit: '100g' },
  { id: 'eg22', name: 'Chicken Pane (Breaded)', category: 'Egyptian', calories: 245, protein: 18, carbs: 15, fats: 13, unit: '100g' },
  { id: 'eg23', name: 'Macarona Bechamel', category: 'Egyptian', calories: 185, protein: 9, carbs: 18, fats: 9, unit: '100g' },
  { id: 'eg24', name: 'Roz Bel Laban', category: 'Egyptian', calories: 120, protein: 3, carbs: 20, fats: 3, unit: '100g' },

  // ============== 🇪🇬 EGYPTIAN DESSERTS ==============
  { id: 'egd1', name: 'Basbousa', category: 'Egyptian Desserts', calories: 345, protein: 4, carbs: 45, fats: 15, unit: '100g' },
  { id: 'egd2', name: 'Konafa', category: 'Egyptian Desserts', calories: 310, protein: 6, carbs: 42, fats: 14, unit: '100g' },
  { id: 'egd3', name: 'Om Ali', category: 'Egyptian Desserts', calories: 280, protein: 7, carbs: 35, fats: 12, unit: '100g' },
  { id: 'egd4', name: 'Balah El Sham', category: 'Egyptian Desserts', calories: 370, protein: 5, carbs: 50, fats: 17, unit: '100g' },
  { id: 'egd5', name: 'Qatayef', category: 'Egyptian Desserts', calories: 300, protein: 6, carbs: 40, fats: 13, unit: '100g' },
  { id: 'egd6', name: 'Zalabya', category: 'Egyptian Desserts', calories: 350, protein: 4, carbs: 52, fats: 14, unit: '100g' },
  { id: 'egd7', name: 'Halawa Tahinia', category: 'Egyptian Desserts', calories: 500, protein: 12, carbs: 50, fats: 28, unit: '100g' },
  { id: 'egd8', name: 'Goulash (Sweet)', category: 'Egyptian Desserts', calories: 320, protein: 5, carbs: 38, fats: 17, unit: '100g' },

  // ============== 🌍 MIDDLE EASTERN DISHES ==============
  { id: 'me1', name: 'Chicken Shawarma (Meat)', category: 'Middle Eastern', calories: 215, protein: 18, carbs: 3, fats: 15, unit: '100g' },
  { id: 'me2', name: 'Beef Shawarma (Meat)', category: 'Middle Eastern', calories: 250, protein: 20, carbs: 4, fats: 17, unit: '100g' },
  { id: 'me3', name: 'Falafel', category: 'Middle Eastern', calories: 333, protein: 13, carbs: 32, fats: 18, unit: '100g' },
  { id: 'me4', name: 'Hummus', category: 'Middle Eastern', calories: 166, protein: 8, carbs: 14, fats: 10, unit: '100g' },
  { id: 'me5', name: 'Baba Ganoush', category: 'Middle Eastern', calories: 130, protein: 2.5, carbs: 10, fats: 9, unit: '100g' },
  { id: 'me6', name: 'Tabbouleh', category: 'Middle Eastern', calories: 90, protein: 2, carbs: 12, fats: 4, unit: '100g' },
  { id: 'me7', name: 'Fattoush', category: 'Middle Eastern', calories: 105, protein: 2, carbs: 12, fats: 5.5, unit: '100g' },
  { id: 'me8', name: 'Kabsa (Saudi)', category: 'Middle Eastern', calories: 175, protein: 12, carbs: 18, fats: 6, unit: '100g' },
  { id: 'me9', name: 'Mandi (Yemeni)', category: 'Middle Eastern', calories: 185, protein: 13, carbs: 19, fats: 7, unit: '100g' },
  { id: 'me10', name: 'Chicken Biryani', category: 'Middle Eastern', calories: 175, protein: 10, carbs: 22, fats: 6, unit: '100g' },
  { id: 'me11', name: 'Mansaf', category: 'Middle Eastern', calories: 220, protein: 11, carbs: 22, fats: 10, unit: '100g' },
  { id: 'me12', name: 'Mulukhiyah with Chicken', category: 'Middle Eastern', calories: 75, protein: 5, carbs: 5, fats: 4, unit: '100g' },
  { id: 'me13', name: 'Kibbeh (Fried)', category: 'Middle Eastern', calories: 265, protein: 12, carbs: 20, fats: 15, unit: '100g' },
  { id: 'me14', name: 'Grape Leaves (Warak Enab)', category: 'Middle Eastern', calories: 120, protein: 3, carbs: 16, fats: 5, unit: '100g' },
  { id: 'me15', name: 'Baklava', category: 'Middle Eastern', calories: 428, protein: 6, carbs: 42, fats: 27, unit: '100g' },

  // ============== 🌎 INTERNATIONAL FAST FOOD ==============
  { id: 'ff1', name: 'Cheese Pizza', category: 'Fast Food', calories: 266, protein: 11, carbs: 33, fats: 10, unit: '100g' },
  { id: 'ff2', name: 'Pepperoni Pizza', category: 'Fast Food', calories: 280, protein: 12, carbs: 30, fats: 13, unit: '100g' },
  { id: 'ff3', name: 'Beef Burger (with Bun)', category: 'Fast Food', calories: 264, protein: 15, carbs: 24, fats: 12, unit: '100g' },
  { id: 'ff4', name: 'Chicken Burger', category: 'Fast Food', calories: 230, protein: 16, carbs: 22, fats: 9, unit: '100g' },
  { id: 'ff5', name: 'Cheeseburger', category: 'Fast Food', calories: 303, protein: 17, carbs: 24, fats: 15, unit: '100g' },
  { id: 'ff6', name: 'Chicken Nuggets', category: 'Fast Food', calories: 296, protein: 15, carbs: 18, fats: 18, unit: '100g' },
  { id: 'ff7', name: 'Hot Dog', category: 'Fast Food', calories: 290, protein: 10, carbs: 24, fats: 17, unit: '100g' },
  { id: 'ff8', name: 'Fried Chicken', category: 'Fast Food', calories: 260, protein: 20, carbs: 10, fats: 16, unit: '100g' },
  { id: 'ff9', name: 'Burrito (Beef)', category: 'Fast Food', calories: 206, protein: 9, carbs: 24, fats: 8, unit: '100g' },
  { id: 'ff10', name: 'Tacos (Beef)', category: 'Fast Food', calories: 195, protein: 10, carbs: 17, fats: 10, unit: '100g' },
  { id: 'ff11', name: 'Doner Kebab', category: 'Fast Food', calories: 215, protein: 16, carbs: 12, fats: 12, unit: '100g' },
  { id: 'ff12', name: 'Crepe (Savory)', category: 'Fast Food', calories: 160, protein: 6, carbs: 16, fats: 8, unit: '100g' },

  // ============== 🍝 INTERNATIONAL DISHES ==============
  { id: 'intl1', name: 'Spaghetti Bolognese', category: 'International', calories: 130, protein: 7, carbs: 14, fats: 5, unit: '100g' },
  { id: 'intl2', name: 'Pasta Alfredo', category: 'International', calories: 170, protein: 6, carbs: 18, fats: 8, unit: '100g' },
  { id: 'intl3', name: 'Lasagna', category: 'International', calories: 166, protein: 9, carbs: 15, fats: 8, unit: '100g' },
  { id: 'intl4', name: 'Sushi Roll (Salmon)', category: 'International', calories: 150, protein: 6, carbs: 22, fats: 4, unit: '100g' },
  { id: 'intl5', name: 'Fried Rice (Chinese)', category: 'International', calories: 168, protein: 4, carbs: 25, fats: 6, unit: '100g' },
  { id: 'intl6', name: 'Pad Thai', category: 'International', calories: 175, protein: 8, carbs: 22, fats: 6, unit: '100g' },
  { id: 'intl7', name: 'Ramen (Instant)', category: 'International', calories: 440, protein: 10, carbs: 60, fats: 18, unit: '100g' },
  { id: 'intl8', name: 'Gyros (Meat)', category: 'International', calories: 215, protein: 14, carbs: 4, fats: 16, unit: '100g' },
  { id: 'intl9', name: 'Caesar Salad', category: 'International', calories: 127, protein: 5, carbs: 7, fats: 9, unit: '100g' },
  { id: 'intl10', name: 'Butter Chicken (Indian)', category: 'International', calories: 148, protein: 12, carbs: 6, fats: 9, unit: '100g' },
  { id: 'intl11', name: 'Tandoori Chicken', category: 'International', calories: 175, protein: 25, carbs: 3, fats: 7, unit: '100g' },
  { id: 'intl12', name: 'Spring Rolls (Fried)', category: 'International', calories: 230, protein: 5, carbs: 25, fats: 12, unit: '100g' },

  // ============== SNACKS & OTHER ==============
  { id: 'sn1', name: 'Dark Chocolate (70%)', category: 'Snacks', calories: 598, protein: 7.8, carbs: 46, fats: 43, unit: '100g' },
  { id: 'sn2', name: 'Honey', category: 'Snacks', calories: 304, protein: 0.3, carbs: 82, fats: 0, unit: '100g' },
  { id: 'sn3', name: 'Granola Bar', category: 'Snacks', calories: 471, protein: 10, carbs: 64, fats: 20, unit: '100g' },
  { id: 'sn4', name: 'Rice Cakes', category: 'Snacks', calories: 387, protein: 8, carbs: 81, fats: 2.8, unit: '100g' },
  { id: 'sn5', name: 'Protein Bar', category: 'Snacks', calories: 380, protein: 30, carbs: 35, fats: 12, unit: '100g' },
  { id: 'sn6', name: 'Milk Chocolate', category: 'Snacks', calories: 535, protein: 8, carbs: 59, fats: 30, unit: '100g' },
  { id: 'sn7', name: 'Popcorn (Air-popped)', category: 'Snacks', calories: 387, protein: 13, carbs: 78, fats: 4.5, unit: '100g' },
  { id: 'sn8', name: 'Potato Chips', category: 'Snacks', calories: 536, protein: 7, carbs: 53, fats: 35, unit: '100g' },
  { id: 'sn9', name: 'Croissant', category: 'Snacks', calories: 406, protein: 8, carbs: 46, fats: 21, unit: '100g' },
  { id: 'sn10', name: 'Ice Cream (Vanilla)', category: 'Snacks', calories: 207, protein: 3.5, carbs: 24, fats: 11, unit: '100g' },
  { id: 'sn11', name: 'Pancakes', category: 'Snacks', calories: 227, protein: 6, carbs: 28, fats: 10, unit: '100g' },
  { id: 'sn12', name: 'Donut (Glazed)', category: 'Snacks', calories: 421, protein: 5, carbs: 53, fats: 22, unit: '100g' },

  // ============== BEVERAGES ==============
  { id: 'bv1', name: 'Orange Juice', category: 'Beverages', calories: 45, protein: 0.7, carbs: 10, fats: 0.2, unit: '100g' },
  { id: 'bv2', name: 'Coconut Water', category: 'Beverages', calories: 19, protein: 0.7, carbs: 3.7, fats: 0.2, unit: '100g' },
  { id: 'bv3', name: 'Almond Milk', category: 'Beverages', calories: 15, protein: 0.6, carbs: 0.3, fats: 1.2, unit: '100g' },
  { id: 'bv4', name: 'Protein Shake', category: 'Beverages', calories: 120, protein: 24, carbs: 5, fats: 1.5, unit: '100g' },
  { id: 'bv5', name: 'Mango Juice', category: 'Beverages', calories: 51, protein: 0.1, carbs: 13, fats: 0.1, unit: '100g' },
  { id: 'bv6', name: 'Sugarcane Juice', category: 'Beverages', calories: 73, protein: 0, carbs: 18, fats: 0, unit: '100g' },
  { id: 'bv7', name: 'Karkade (Hibiscus)', category: 'Beverages', calories: 37, protein: 0.4, carbs: 7.4, fats: 0, unit: '100g' },
  { id: 'bv8', name: 'Sahlab', category: 'Beverages', calories: 95, protein: 2, carbs: 14, fats: 3.5, unit: '100g' },
  { id: 'bv9', name: 'Cola Soda', category: 'Beverages', calories: 42, protein: 0, carbs: 11, fats: 0, unit: '100g' },
  { id: 'bv10', name: 'Arabic Coffee', category: 'Beverages', calories: 2, protein: 0.1, carbs: 0, fats: 0, unit: '100g' },
];
